version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
    ports:
      - "8080:8080"
    command: ["start-dev"]
  #sentinel-dashboard:
    #image: bladex/sentinel-dashboard:latest
    #container_name: sentinel-dashboard
    #ports:
      #- "8858:8858"
    #restart: always
  redis:
    image: redis:7.0-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
volumes:
  redis_data: