spring:
  application:
    name: grpc-client-demo
  grpc:
    client:
      channels:
        local:
          address: 0.0.0.0:9090
  #security:
    #user:
      #name: user
      #password: password
server:
  port: 8082
