spring:
  application:
    name: grpc-server-demo
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
          issuer-uri: http://localhost:9000
  cloud:
    consul:
      discovery:
        tags: myWebTag
server:
  port: 8010
grpc:
  port: 0
  enable-reflection: true
  consul:
    discovery:
      tags: myGrpc
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"