server:
  port: 8088
spring:
  application:
    name: dubbo-provider
dubbo:
  protocol:
    name: tri
    port: 50051
  registry:
    address: 'nacos://localhost:8848'
    username: nacos
    password: nacos
    #register-mode: instance
  scan:
    base-packages: com.example.dubbo