spring:
  cloud:
    stream:
      bindings:
        supplier-out-0:
          destination: batch-in
        process-in-0:
          destination: batch-in
          group: process-group
          consumer:
            batch-mode: true
        process-out-0:
          destination: batch-out
        consumer-in-0:
          destination: batch-out
          group: consumer-group
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          process-in-0:
            consumer:
              configuration:
                # Forces consumer to wait 5 seconds before polling for messages
                fetch.max.wait.ms: 5000
                fetch.min.bytes: 1000000000
                max.poll.records: 10000000
    function:
      definition: supplier;process;consumer
server:
  port: 8084